
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import type { Metadata } from "next";
import QueryClientProvider from "./QueryClientProvider";


export const metadata: Metadata = {
  title: "Products Panel",
  description: "Generated by create next app and Ant Design",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <QueryClientProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </QueryClientProvider>
      </body>
    </html>
  );
}
